---
application:
  name: "tgvc-userbot"
  project: "tgvcuserbott "
  organization: "QoveryCommunity"
routers:
- name: "main-tgvc-userbot"
  routes:
  - application_name: "tgvc-userbot"
    paths:
    - "/*"
